/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pb_input_t, pb_input_t, AUTO)


PB_BIND(pb_voltage_t, pb_voltage_t, AUTO)


PB_BIND(pb_message_t, pb_message_t, AUTO)




